# Generated by Django 3.1.5 on 2021-06-02 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='querie',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('timest', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
